# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Ben Wyrosdick"
description: > # this means to ignore newlines until "email:"
   Personal & Techical Blog

email: ben.wyrosdick@gmail.com
#blog logo
logo: "/assets/images/bw_logo.png"
# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Ben Wyrosdick'
author: 'Ben Wyrosdick'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://wyrosdick.com"
baseurl: ""
#used to display twitter cards
twitter_handle: '@benwyrosdick'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/benwyrosdick
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/benwyrosdick
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:

