# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ben Wyrosdick
name: Ben Wyrosdick
email: ben.wyrosdick@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog and random musings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wyrosdick.com"
twitter_username: benwyrosdick
github_username:  benwyrosdick
keybase_username:  benwyrosdick
yc_username:  benwyrosdick

# Build settings
markdown: kramdown

gems:
  - octopress-debugger
